"""
Podcast notes generator.
Creates structured notes from podcast listening sessions.
"""

import json
from dataclasses import dataclass, asdict
from datetime import datetime
from pathlib import Path


@dataclass
class PodcastNote:
    """A note for a podcast episode."""
    episode_id: str
    episode_name: str
    show_name: str
    description: str
    duration_ms: int
    listened_ms: int
    timestamp: str
    user_notes: str = ""
    key_topics: list[str] | None = None
    mood: str = ""

    @property
    def listened_percentage(self) -> int:
        if self.duration_ms == 0:
            return 0
        return int((self.listened_ms / self.duration_ms) * 100)

    def to_markdown(self) -> str:
        """Convert note to markdown format."""
        topics = ""
        if self.key_topics:
            topics = "\n**Key Topics:**\n" + "\n".join(f"- {t}" for t in self.key_topics)

        user_section = ""
        if self.user_notes:
            user_section = f"\n**My Notes:**\n{self.user_notes}"

        return f"""## {self.episode_name}

**Show:** {self.show_name}
**Date:** {self.timestamp[:10]}
**Listened:** {self.listened_percentage}%
{topics}
{user_section}

---
"""

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict) -> "PodcastNote":
        return cls(**data)


class NotesManager:
    """Manages podcast notes storage and retrieval."""

    def __init__(self, data_dir: Path):
        self.data_dir = data_dir
        self.notes_file = data_dir / "podcast_notes.json"
        self.markdown_file = data_dir / "podcast_notes.md"
        self.notes: list[PodcastNote] = []
        self._load()

    def _load(self) -> None:
        """Load notes from disk."""
        if self.notes_file.exists():
            try:
                with open(self.notes_file, "r") as f:
                    data = json.load(f)
                    self.notes = [PodcastNote.from_dict(n) for n in data]
            except (json.JSONDecodeError, KeyError):
                self.notes = []

    def _save(self) -> None:
        """Save notes to disk (both JSON and Markdown)."""
        self.data_dir.mkdir(parents=True, exist_ok=True)

        # Save JSON
        with open(self.notes_file, "w") as f:
            json.dump([n.to_dict() for n in self.notes], f, indent=2)

        # Save Markdown
        with open(self.markdown_file, "w") as f:
            f.write("# Podcast Notes\n\n")
            f.write(f"*Generated by Spotify AI Agent*\n\n")
            for note in sorted(self.notes, key=lambda n: n.timestamp, reverse=True):
                f.write(note.to_markdown())

    def add_note(
        self,
        episode_id: str,
        episode_name: str,
        show_name: str,
        description: str,
        duration_ms: int,
        listened_ms: int,
        user_notes: str = "",
        key_topics: list[str] | None = None,
        mood: str = "",
    ) -> PodcastNote:
        """Add a new podcast note."""
        # Check if note already exists for this episode
        existing = next((n for n in self.notes if n.episode_id == episode_id), None)

        if existing:
            # Update existing note
            existing.listened_ms = max(existing.listened_ms, listened_ms)
            if user_notes:
                existing.user_notes = user_notes
            if key_topics:
                existing.key_topics = key_topics
            note = existing
        else:
            # Create new note
            note = PodcastNote(
                episode_id=episode_id,
                episode_name=episode_name,
                show_name=show_name,
                description=description[:500] if description else "",  # Truncate long descriptions
                duration_ms=duration_ms,
                listened_ms=listened_ms,
                timestamp=datetime.now().isoformat(),
                user_notes=user_notes,
                key_topics=key_topics,
                mood=mood,
            )
            self.notes.append(note)

        self._save()
        return note

    def get_note(self, episode_id: str) -> PodcastNote | None:
        """Get note for a specific episode."""
        return next((n for n in self.notes if n.episode_id == episode_id), None)

    def get_notes_for_show(self, show_name: str) -> list[PodcastNote]:
        """Get all notes for a show."""
        return [n for n in self.notes if n.show_name.lower() == show_name.lower()]

    def get_recent_notes(self, limit: int = 10) -> list[PodcastNote]:
        """Get most recent notes."""
        sorted_notes = sorted(self.notes, key=lambda n: n.timestamp, reverse=True)
        return sorted_notes[:limit]

    def search_notes(self, query: str) -> list[PodcastNote]:
        """Search notes by keyword."""
        query_lower = query.lower()
        return [
            n for n in self.notes
            if query_lower in n.episode_name.lower()
            or query_lower in n.show_name.lower()
            or query_lower in n.user_notes.lower()
            or (n.key_topics and any(query_lower in t.lower() for t in n.key_topics))
        ]

    def get_stats(self) -> dict:
        """Get notes statistics."""
        if not self.notes:
            return {"total": 0, "shows": {}, "total_listened_hours": 0}

        shows: dict[str, int] = {}
        total_listened_ms = 0

        for note in self.notes:
            shows[note.show_name] = shows.get(note.show_name, 0) + 1
            total_listened_ms += note.listened_ms

        return {
            "total": len(self.notes),
            "shows": shows,
            "total_listened_hours": round(total_listened_ms / (1000 * 60 * 60), 1),
        }
